#define RIGHT_MOVEMENT 2
#define LEFT_MOVEMENT 3
#define UP_MOVEMENT 4
#define DOWN_MOVEMENT 5
#define ACTION 6

#define SCREEN_HEIGHT 96
#define SCREEN_WIDTH 120

#define EYE_HEIGHT 3
#define EYE_WIDTH 8

#define ENEMY_HEIGHT 16
#define ENEMY_WIDTH 12
#define ENEMY_DISABLED 0
#define ENEMY_ENABLED 1

#define TIME_MARCO_POLO 12
#define MARCO_POLO_CHANCES 4
#define MARCO_POLO_SHOWING_TIME 35

#define GAME_DURATION 120
#define DURATION_TO_SHOW_FOUND_SINALIZATION 50

enum GAME_STATES { IN_START_SCREEN = 1, PLAYING, LOST, WIN };