#define RIGHT_MOVEMENT 2
#define LEFT_MOVEMENT 3
#define UP_MOVEMENT 4
#define DOWN_MOVEMENT 5
#define ACTION 6

#define SCREEN_HEIGHT 96
#define SCREEN_WIDTH 120

#define EYE_HEIGHT 3
#define EYE_WIDTH 8

#define ENEMY_HEIGHT 4
#define ENEMY_WIDTH 4

#define TIME_MARCO_POLO 12
#define MARCO_POLO_CHANCES 3
#define MARCO_POLO_SHOWING_TIME 50

#define GAME_DURATION 10000